name = "MyAwesomePackage"
uuid = "af0bab95-7150-4a84-a927-f848fcbcc392"
authors = ["Matthew Kehoe <mkehoe@mtu.edu>"]
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = "0.21, 0.22"
julia = "1.9.1"
